version: '1.0.{build}'
image: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    qt: 5.13
    msvc: msvc2017
    vs: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build
    QTDIR: C:\Qt\5.13.2\msvc2017_64
    ProjectName: GenshinImpactNaturalLaw
    ProJectExeName: TianLi_Launcher
    MyProjectDir: C:\projects\%ProjectName%
    Lib7zExeDll: https://github.com/GengGode/7zExeDllRelease/releases/download/1.0.0/Release.zip

skip_tags: true

before_build: 
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    #- set PATH=%PATH%;%QTDIR%\bin;
    #- set vcvarsall=%vs%\vcvarsall.bat
    #- call "%vcvarsall%" x64
    - echo %LANG%
    - set PATH=%PATH%;%QTDIR%\bin;
    - call %QTDIR%\bin\qtenv2.bat
    - call %vs%\vcvars64.bat x64
    
build_script:
    #- MSBuild %MyProjectDir%TianLiInstallationPackage\TianLiInstallationPackage.vcxproj
    - cd %MyProjectDir%\%ProjectName%
    - qmake
    - nmake
    
after_build:
    # copy include and source code files\
    - mkdir %MyProjectDir%\x64\build\
    - cd %MyProjectDir%\x64\build\
    - appveyor DownloadFile %Lib7zExeDll%
    - 7z x ./Release.zip -y -o./
    - rm -f ./Release.zip

    - cd %MyProjectDir%\x64\Release\
    #- ren *.exe tmp.exe
    - copy %MyProjectDir%\x64\Release\%ProJectExeName%.exe %MyProjectDir%\x64\build\
   
    - cd %MyProjectDir%\x64\build\
    - windeployqt %ProJectExeName%.exe 
    
    
    
    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    - 7z a source.7z %MyProjectDir%\x64\build\*
    
    - appveyor PushArtifact version.tag
    - appveyor PushArtifact source.7z
    
deploy:
    - provider: GitHub
      description:  '$(APPVEYOR_PROJECT_SLUG): $(ProJectExeName) $(APPVEYOR_BUILD_VERSION)' 
      auth_token:
         secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
      draft: false
      tag: $(APPVEYOR_BUILD_VERSION)
      force_update: true
      on:  
        APPVEYOR_REPO_TAG: false

notifications:
  - provider: Email
    to:
      - ysx20201030@163.com
    subject: '{{status}}: {{projectName}} {{buildVersion}}'                  # optional
    message: "Commit #{{commitId}} by {{commitAuthor}} on {{commitDate}}: {{commitMessage}}"    # optional
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false
