version: '1.0.{build}'
image: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    qt: 5.14
    msvc: msvc2017
    vs: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build
    QTDIR: C:\Qt\5.14.2\msvc2017_64
    ProjectName: GenshinImpactNaturalLaw
    ProJectExeName: "\xE5A4A9\xE79086\xE7B3BB\xE7BB9F"
    MyProjectDir: C:\projects\%ProjectName%
    
skip_tags: true

before_build: 
    #- set PATH=%PATH%;%QTDIR%\bin;
    #- set vcvarsall=%vs%\vcvarsall.bat
    #- call "%vcvarsall%" x64
    - set PATH=%PATH%;%QTDIR%\bin;
    - call %QTDIR%\bin\qtenv2.bat
    - call %vs%\vcvars64.bat x64
    
build_script:
    #- MSBuild %MyProjectDir%TianLiInstallationPackage\TianLiInstallationPackage.vcxproj
    - cd %MyProjectDir%\%ProjectName%
    - qmake
    - nmake
    
after_build:
    # copy include and source code files
    #- ls
    - chcp 65001
    - mkdir %MyProjectDir%\x64\build\
    - ps: cp -r $env:MyProjectDir\x64\Release\$env:ProJectExeName.exe $env:MyProjectDir\x64\build\
    - cd %MyProjectDir%\x64\build\
    - echo  %MyProjectDir%\x64\Release\%ProJectExeName%.exe
    - dir %MyProjectDir%\x64\Release\
    - dir %MyProjectDir%\x64\build\
    - windeployqt %ProJectExeName%.exe

    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    - 7z a %ProJectExeName%.7z %MyProjectDir%\x64\build\*
    - appveyor PushArtifact version.tag
    - appveyor PushArtifact %ProJectExeName%.7z
    
deploy:
    - provider: GitHub
      description:  '$(APPVEYOR_PROJECT_SLUG): $(ProJectExeName) $(APPVEYOR_BUILD_VERSION)' 
      auth_token:
         secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
      draft: false
      tag: $(APPVEYOR_BUILD_VERSION)
      force_update: true
      on:  
        APPVEYOR_REPO_TAG: false

notifications:
  - provider: Email
    to:
      - ysx20201030@163.com
    subject: '{{status}}: {{projectName}} {{buildVersion}}'                  # optional
    message: "Commit #{{commitId}} by {{commitAuthor}} on {{commitDate}}: {{commitMessage}}"    # optional
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false
