name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Release


permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      # 需要两个机密：
      # 1. ALICLOUD_CLI_UPADTE_CONFIGYAML 文件上传配置
      # 2. UPDATE_ARTIFACT_TOKEN 版本更新token
      PROJECT_NAME: GenshinImpactNaturalLaw
      PROJECT_BUILD_NAME: 天理启动器
      Qt_Dir_Static : D:/a/${PROJECT_NAME}/${PROJECT_NAME}/deps_qt/5.15.7/
      ProjectName: ${PROJECT_NAME}
    steps:
    - uses: actions/checkout@v3
    - name: Add Deps_Qt
      run: |
        git clone http://github.com/GenshinTianLiBattle/deps_qt.git
        cd deps_qt
        .\unzip.bat
        Copy-Item -Path "openssl" -Destination "C:\" -Recurse
        dir
        cd ..
        dir
        echo PROJECT_NAME: ${PROJECT_NAME}
        echo PROJECT_NAME: $PROJECT_NAME
        copy deps_qt/QtMsBuild.7z ${PROJECT_NAME}/
        copy deps_qt/7z.exe ${PROJECT_NAME}/
        copy deps_qt/7z.dll ${PROJECT_NAME}/
        cd ${PROJECT_NAME}
        7z.exe x QtMsBuild.7z   
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Test Version
      run: |
        .\x64\${{env.BUILD_CONFIGURATION}}\${PROJECT_BUILD_NAME}.exe -V
        .\x64\${{env.BUILD_CONFIGURATION}}\${PROJECT_BUILD_NAME}.exe -v | out-file version.ver
        .\x64\${{env.BUILD_CONFIGURATION}}\${PROJECT_BUILD_NAME}.exe -V | out-file build_version.ver
    - name: Make Zip Pkg
      run: |
        $version = Get-Content version.ver
        echo (Get-Content build_version.ver)
        .\${PROJECT_NAME}\7z.exe a -tZip ${PROJECT_BUILD_NAME}-$version.zip D:\a\${PROJECT_NAME}\${PROJECT_NAME}/x64\${{env.BUILD_CONFIGURATION}}\${PROJECT_BUILD_NAME}.exe
        dir
        (Get-FileHash -Path ${PROJECT_BUILD_NAME}-$version.zip -Algorithm MD5).Hash | out-file md5.hash
        echo (Get-Content md5.hash)
        
    - name: Upload To Download site
      run: |
        $version = Get-Content version.ver
        curl -L "https://github.com/aoaostar/alidrive-uploader/releases/download/v2.2.1/alidrive_uploader_v2.2.1_windows_amd64.zip" -o alidrive.zip 
        tar -xf alidrive.zip --strip-components 1
        dir
        del example.config.yaml
        Out-File -FilePath config.yaml -InputObject "${{secrets.ALICLOUD_CLI_UPADTE_CONFIGYAML}}"
        .\alidrive.exe .\${PROJECT_BUILD_NAME}-$version.zip / ${PROJECT_NAME}
        
    - name: Update Api Version
      run: |
        $version = Get-Content version.ver
        $buildversion = Get-Content build_version.ver
        $md5 = Get-Content md5.hash
        $commitLog = git log -1 --pretty=%B
        
        $token="${{secrets.UPDATE_ARTIFACT_TOKEN}}"
        $url='http://update.api.weixitianli.com/${PROJECT_NAME}/Version?token='+$token
        $body='{"version": "'+$version+'", "description": "' + $buildVersion + '", "downloadUrl": "http://download.weixitianli.com/d/TianLiUpdateService/' + '${PROJECT_NAME}' + '/' + '${PROJECT_BUILD_NAME}' + '-' + $version + '.zip", "hash": "' + $md5 + '", "updateLog": "' + $commitLog + '"}'
        echo $url
        echo $body
        Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType 'application/json'
        
    - name: Copy Pkg
      run: |
        mkdir  D:\a\${PROJECT_NAME}\${PROJECT_NAME}/artifact
        copy  D:\a\${PROJECT_NAME}\${PROJECT_NAME}/x64/${{env.BUILD_CONFIGURATION}}/*.exe  D:\a\${PROJECT_NAME}\${PROJECT_NAME}/artifact
        cd D:\a\${PROJECT_NAME}\${PROJECT_NAME}/artifact
        dir
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${PROJECT_BUILD_NAME}
        path: D:\a\${PROJECT_NAME}\${PROJECT_NAME}/x64/${{env.BUILD_CONFIGURATION}}/*.exe
        if-no-files-found: 'warn'
