name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  
  BUILD_CONFIGURATION: Release


permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      # 需要两个机密：
      # 1. ALICLOUD_CLI_UPADTE_CONFIGYAML 文件上传配置
      # 2. UPDATE_ARTIFACT_TOKEN 版本更新token
      # PROJECT_NAME: GenshinImpactNaturalLaw
      # PROJECT_BUILD_NAME: 天理启动器
      Qt_Dir_Static : D:/a/GenshinImpactNaturalLaw/GenshinImpactNaturalLaw/deps_qt/5.15.7/
      ProjectName: GenshinImpactNaturalLaw
    steps:
    - uses: actions/checkout@v3
    - name: Add Deps_Qt
      run: |
        git clone http://github.com/GenshinTianLiBattle/deps_qt.git
        cd deps_qt
        .\unzip.bat
        Copy-Item -Path "openssl" -Destination "C:\" -Recurse
        dir
        cd ..
        dir
        copy deps_qt/QtMsBuild.7z GenshinImpactNaturalLaw/
        copy deps_qt/7z.exe GenshinImpactNaturalLaw/
        copy deps_qt/7z.dll GenshinImpactNaturalLaw/
        cd GenshinImpactNaturalLaw
        7z.exe x QtMsBuild.7z   
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Test Version
      run: |
        .\x64\${{env.BUILD_CONFIGURATION}}\天理启动器.exe -V
        .\x64\${{env.BUILD_CONFIGURATION}}\天理启动器.exe -v | out-file version.ver
        .\x64\${{env.BUILD_CONFIGURATION}}\天理启动器.exe -V | out-file build_version.ver
    - name: Make Zip Pkg
      run: |
        $version = Get-Content version.ver
        echo (Get-Content build_version.ver)
        .\GenshinImpactNaturalLaw\7z.exe a -tZip 天理启动器-$version.zip D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/x64\${{env.BUILD_CONFIGURATION}}\天理启动器.exe
        dir
        (Get-FileHash -Path 天理启动器-$version.zip -Algorithm MD5).Hash | out-file md5.hash
        echo (Get-Content md5.hash)
        
    - name: Upload To Download site
      run: |
        $version = Get-Content version.ver
        curl -L "https://github.com/aoaostar/alidrive-uploader/releases/download/v2.2.1/alidrive_uploader_v2.2.1_windows_amd64.zip" -o alidrive.zip 
        tar -xf alidrive.zip --strip-components 1
        dir
        del example.config.yaml
        Out-File -FilePath config.yaml -InputObject "${{secrets.ALICLOUD_CLI_UPADTE_CONFIGYAML}}"
        .\alidrive.exe .\天理启动器-$version.zip / GenshinImpactNaturalLaw
        
    - name: Update Api Version
      run: |
        $version = Get-Content version.ver
        $buildversion = Get-Content build_version.ver
        $md5 = Get-Content md5.hash
        $commitLog = git log -1 --pretty=%B
        
        $token="${{secrets.UPDATE_ARTIFACT_TOKEN}}"
        $url='http://update.api.weixitianli.com/GenshinImpactNaturalLaw/Version?token='+$token
        $body='{"version": "'+$version+'", "description": "' + $buildVersion + '", "downloadUrl": "http://download.weixitianli.com/d/TianLiUpdateService/' + 'GenshinImpactNaturalLaw' + '/' + '天理启动器' + '-' + $version + '.zip", "hash": "' + $md5 + '", "updateLog": "' + $commitLog + '"}'
        echo $url
        echo $body
        Invoke-RestMethod -Method Post -Uri $url -Body $body -ContentType 'application/json'
        
    - name: Copy Pkg
      run: |
        mkdir  D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/artifact
        copy  D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/x64/${{env.BUILD_CONFIGURATION}}/*.exe  D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/artifact
        cd D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/artifact
        dir
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: 天理启动器
        path: D:\a\GenshinImpactNaturalLaw\GenshinImpactNaturalLaw/x64/${{env.BUILD_CONFIGURATION}}/*.exe
        if-no-files-found: 'warn'
