name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      Qt_Dir_Static : D:/a/GenshinTianLiBattleClient/GenshinTianLiBattleClient/deps_qt/5.15.7/
      ProjectName: GenshinImpact_TianLi
    steps:
    - uses: actions/checkout@v3
    - name: Add Deps_Qt
      run: |
        git clone http://github.com/GenshinTianLiBattle/deps_qt.git
        cd deps_qt
        .\unzip.bat
        Copy-Item -Path "openssl" -Destination "C:\" -Recurse
        cd ..
        dir
        copy deps_qt/QtMsBuild.7z $(ProjectName)/
        copy deps_qt/7z.exe $(ProjectName)/
        copy deps_qt/7z.dll $(ProjectName)/
        cd $(ProjectName)
        7z.exe x QtMsBuild.7z   
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
